# Generated by Django 2.2.1 on 2019-06-06 19:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('firstPicture', models.ImageField(upload_to='picture/%Y/%m', verbose_name='首图')),
                ('flag', models.CharField(max_length=20, verbose_name='标记')),
                ('views', models.IntegerField(default=0, verbose_name='浏览次数')),
                ('appreciate', models.BooleanField(default=False, verbose_name='能否赞赏')),
                ('sharestatement', models.BooleanField(default=False, verbose_name='能否分享')),
                ('commentabled', models.BooleanField(default=True, verbose_name='能否评论')),
                ('published', models.BooleanField(default=False, verbose_name='是否发布')),
                ('recommend', models.BooleanField(default=False, verbose_name='是否推荐')),
                ('createtime', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('updatetime', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='标签名称')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='分类名称')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=20, verbose_name='昵称')),
                ('email', models.TextField(verbose_name='评论内容')),
                ('avatar', models.ImageField(default='image/default.png', upload_to='avatar/%Y/%m', verbose_name='头像')),
                ('createtime', models.DateTimeField(default=datetime.datetime.now, verbose_name='评论时间')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Article', verbose_name='文章')),
                ('commentparent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Comment', verbose_name='上级评论')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(to='articles.Tag', verbose_name='文章标签'),
        ),
        migrations.AddField(
            model_name='article',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Type', verbose_name='文章类型'),
        ),
    ]
