# Generated by Django 2.2.1 on 2019-06-10 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20190610_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='flag',
            field=models.CharField(choices=[('yc', '原创'), ('zz', '转载'), ('fy', '翻译')], default='yc', max_length=20, verbose_name='标记'),
        ),
    ]
