# Generated by Django 2.2.1 on 2019-06-12 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20190612_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commentparent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.Comment', verbose_name='上级评论'),
        ),
    ]
