# Generated by Django 2.2.1 on 2019-06-12 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190612_1611'),
        ('articles', '0009_auto_20190612_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='comments', to='users.UserFree', verbose_name='免费用户'),
        ),
    ]
