# Generated by Django 2.2.1 on 2019-06-13 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_comment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='flag',
            field=models.CharField(choices=[('原创', '原创'), ('原创', '转载'), ('翻译', '翻译')], default='原创', max_length=20, verbose_name='标记'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='replies', to='users.UserFree', verbose_name='回复给'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='root',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='root_comment', to='articles.Comment', verbose_name='根评论'),
        ),
    ]
